version: "3.9"

services:
  db:
    image: postgres:15
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      - SLEEP_INTERVAL_EXTRACT=10
      - SLEEP_INTERVAL_TRANSFORM=11
    command: ["./start-cron.sh"]
#    command: cron && tail -f /var/log/myscript.log

volumes:
  db_data:
